-- MySQL Script generated by MySQL Workbench
-- Sun Dec  4 10:48:17 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_syria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_syria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_syria` DEFAULT CHARACTER SET utf8 ;
USE `DB_syria` ;

-- -----------------------------------------------------
-- Table `DB_syria`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_syria`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `updated_at` DATETIME NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
